import React from 'react'

interface Gazeta006Props {
  className?: string
}

export default function Gazeta006({ className }: Gazeta006Props) {
  return (
    <div className={className}>
      <h1>JUNTA DE HISTORIA Y NUMISMÁTICA AMERICANA</h1>
<h2>Presidente</h2>
<p>SEÑOR ENRIQUE PEÑA</p>
<h2>Vice Presidente 1.º</h2>
<p>DOCTOR RAMÓN J. CÁRCANO</p>
<h2>Vice Presidente 2.º</h2>
<p>SEÑOR SAMUEL A. LAFONE QUEVEDO</p>
<h2>Secretario</h2>
<p>DOCTOR JOSÉ MARCÓ DEL PONT</p>
<h2>ProSecretario-Tesorero</h2>
<p>DOCTOR JORGE A. ECHAYDE</p>
<h2>Miembros activos</h2>
<ul>
<li>SEÑOR AMADEO JUAN CARLOS</li>
<li>SEÑOR AMBROSETTI JUAN B.</li>
<li>SEÑOR CADELAGO ANTONIO</li>
<li>SEÑOR CANTILLO JOSÉ LUIS</li>
<li>SEÑOR CANTILLO JOSÉ LUIS ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N.</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTONIO</li>
<li>SEÑOR CARRANZA PEDRO N. ANTON
    </div>
  )
}

export { Gazeta006 }
