import fs from 'fs';
import path from 'path';

interface ParsedContentData {
  pageNumber: number;
  content: string;
  generatedAt: string;
}

export default async function ParsedContentWithStyledJsx({ page }: { page: string }) {
  // Extract page number from filename (e.g., "gazeta_006.jpg" -> "006")
  const pageNumber = page.replace(/\.jpg$/, '').replace(/^gazeta_/, '');
  
  // Construct path to the JSON file generated by the parse script
  const jsonFilePath = path.join(process.cwd(), `gazeta_${pageNumber}.json`);
  
  // Check if parsed content exists
  let parsedData: ParsedContentData | null = null;
  let hasContent = false;
  
  try {
    if (fs.existsSync(jsonFilePath)) {
      const jsonContent = fs.readFileSync(jsonFilePath, 'utf8');
      parsedData = JSON.parse(jsonContent);
      hasContent = true;
    }
  } catch (error) {
    console.error('Error reading parsed content:', error);
  }

  return (
    <div className="h-full flex flex-col">
      <header className="px-4 py-3 border-b border-slate-200">
        <h2 className="text-lg font-semibold text-slate-800">
          {hasContent ? 'Parsed Content' : 'No Parsed Content'}
        </h2>
        {hasContent && parsedData && (
          <p className="text-sm text-slate-500 mt-1">
            Generated {new Date(parsedData.generatedAt).toLocaleDateString()}
          </p>
        )}
      </header>
      
      <div className="flex-1 overflow-auto p-4 bg-white dark:bg-gray-900">
        {hasContent && parsedData ? (
          <article 
            className="prose-content"
            dangerouslySetInnerHTML={{ __html: parsedData.content }}
          />
        ) : (
          <div className="text-center text-slate-500 pt-8">
            <div className="mb-4">
              <svg className="w-12 h-12 mx-auto text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <p className="mb-2">No parsed content found for this page.</p>
            <p className="text-sm">Run the parser to generate content:</p>
            <code className="text-xs bg-slate-200 px-2 py-1 rounded mt-2 inline-block">
              bun parse --page="{pageNumber}"
            </code>
          </div>
        )}
      </div>
      
      <style jsx>{`
        .prose-content {
          color: #1f2937;
          max-width: 65ch;
          line-height: 1.75;
          font-size: 1.125rem;
          max-width: none;
        }

        .prose-content > * + * {
          margin-top: 1.3333333em;
        }

        .prose-content h1 {
          color: #111827;
          font-weight: 800;
          font-size: 2.25rem;
          line-height: 2.5rem;
          margin-bottom: 1rem;
          margin-top: 0;
        }

        .prose-content h2 {
          color: #111827;
          font-weight: 700;
          font-size: 1.875rem;
          line-height: 2.25rem;
          margin-bottom: 0.75rem;
          margin-top: 2rem;
        }

        .prose-content h3 {
          color: #111827;
          font-weight: 600;
          font-size: 1.5rem;
          line-height: 2rem;
          margin-bottom: 0.5rem;
          margin-top: 1.5rem;
        }

        .prose-content h4 {
          color: #111827;
          font-weight: 600;
          font-size: 1.25rem;
          line-height: 1.75rem;
          margin-bottom: 0.5rem;
          margin-top: 1.25rem;
        }

        .prose-content p {
          color: #374151;
          margin-bottom: 1.25rem;
          line-height: 1.75;
        }

        .prose-content ul {
          list-style-type: disc;
          margin-left: 1.625rem;
          margin-bottom: 1.25rem;
        }

        .prose-content ol {
          list-style-type: decimal;
          margin-left: 1.625rem;
          margin-bottom: 1.25rem;
        }

        .prose-content li {
          color: #374151;
          margin-bottom: 0.5rem;
          line-height: 1.75;
        }

        .prose-content strong {
          color: #111827;
          font-weight: 600;
        }

        .prose-content a {
          color: #3b82f6;
          text-decoration: underline;
          font-weight: 500;
        }

        .prose-content a:hover {
          color: #1d4ed8;
        }

        @media (prefers-color-scheme: dark) {
          .prose-content {
            color: #e5e7eb;
          }

          .prose-content h1,
          .prose-content h2,
          .prose-content h3,
          .prose-content h4,
          .prose-content strong {
            color: #f9fafb;
          }

          .prose-content p,
          .prose-content li {
            color: #d1d5db;
          }

          .prose-content a {
            color: #60a5fa;
          }

          .prose-content a:hover {
            color: #93c5fd;
          }
        }
      `}</style>
    </div>
  );
}
